[build]
  command = "npm install"
  functions = "functions"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  external_node_modules = ["express", "sqlite3"]
  included_files = ["*.db"] 